version: 2
jobs:
  end2end:
      docker:
        - image: python:3.6
      resource_class: large
      steps:
        - checkout
        - run: python3 -m pip install --user tox awscli
        - run: python3 -m awscli configure set region us-east-1
        - run:
            command: python3 -m tox -- -v
            no_output_timeout: 180m

workflows:
  version: 2
  build:
    jobs:
      - end2end:
          context: flambe-publisher
