version: 2
jobs:
  test:
      docker:
        - image: python:3.6
      steps:
        - checkout
        - run: echo $TWINE_USERNAME
workflows:
  version: 2
  build:
    jobs:
      - test:
           context: flambe-publisher
